# Generated by Django 3.2.3 on 2021-06-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='level_of_knowledge_english',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='word',
            name='level_of_knowledge_polish',
            field=models.IntegerField(default=1),
        ),
    ]
